package com.queatz.ailaai

sealed class AppNav(val route: String) {
    data object Shopping : AppNav("shopping")
    data object Schedule : AppNav("schedule")
    data object Reminders : AppNav("reminders")
    data object Explore : AppNav("explore")
    data object Write : AppNav("write")
    data object Messages : AppNav("messages")
    data object Inventory : AppNav("inventory")
    data object Items : AppNav("items")
    data object StickerPacks : AppNav("sticker-packs")
    data object Me : AppNav("me")
    data object Settings : AppNav("settings")
    class Profile(id: String) : AppNav("profile/$id")
    class EditProfile(id: String) : AppNav("profile/$id/edit")
    class Group(id: String) : AppNav("group/$id")
    class Page(id: String) : AppNav("card/$id")
    class Story(id: String) : AppNav("story/$id")
    class WriteStory(id: String) : AppNav("write/$id")
    class Reminder(id: String) : AppNav("reminder/$id")
    class EditReminder(id: String) : AppNav("reminder/$id/edit")
    class EditCard(id: String) : AppNav("card/$id/edit")
    class StickerPack(id: String) : AppNav("sticker-pack/$id")
    class EditStickerPack(id: String) : AppNav("sticker-pack/$id/edit")
    class LinkDevice(token: String) : AppNav("link-device/$token")
}
