#! /bin/bash

if ./gradlew :shadowJar && \
  read -n 1 -s -r -p "Press any key to continue..." && echo && \
  sftp 'root@api.ailaai.app:/root' <<< $'put "build/libs/Ai La Ai Backend-all.jar"' && \
  read -n 1 -s -r -p "Press any key to continue..." && echo && \
  ssh root@api.ailaai.app 'cd /root && ./r'; then
  echo "Success"
else
  echo "Failed"
fi
