package components
import androidx.compose.runtime.Composable
import appText
import org.jetbrains.compose.web.css.*
import org.jetbrains.compose.web.dom.Div
import org.jetbrains.compose.web.dom.H3
import org.jetbrains.compose.web.dom.Text
import r

@Composable
fun PrivacyPage() {
    Div({
        style {
            property("margin", "${1.r} auto")
            maxWidth(1200.px)
            padding(0.r, 1.r, 1.r, 1.r)
            fontSize(22.px)
            lineHeight("1.5")
            minHeight(100.vh)
        }
    }) {
        H3 {
            appText { privacyPolicy }
        }
        Div({
            style {
                whiteSpace("pre-wrap")
            }
        }) {
            Text("""
                Platform - The platform these terms apply to.
                You - Any person using the Platform.
                People - All humans and animals
                
                Most data created by You that is not made accessible publicly on the Platform is not accessed or provided to any other entity except when required by law and to resolve reports.
                
                Some anonymized data generated by your use of the Platform IS made available publicly to support different useful tools for people.  Examples include: search trends by city, number of active people by city.
                
                Please reach out for specific questions to get exact answers.
                """.trimIndent())
        }
    }
}
