-keep class io.ktor.** { *; }
-keep class kotlinx.** { *; }
-keep class androidx.** { *; }
-keep class com.queatz.** { *; }
-keep class com.huawei.** { *; }
-keep class org.bouncycastle.** { *; }

-renamesourcefileattribute SourceFile
-ignorewarnings
-keepattributes *Annotation*
-keepattributes Exceptions
-keepattributes InnerClasses
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable
